package com.autogen.utils;

public class PromptUtils {
    private PromptUtils(){}
    private static final String DOUBLE_BLANK_LINE = "\n\n";

    public static String combineTestAndResult(String testContent, String result){
        //TODO: Complete the prompt.
        return testContent + result;
    }
    public static String prompting(String raw, PromptType type){
        String out = "";
        switch (type){
            case PDF_SUBMIT:{
                out = pdfPrompt(raw);
                break;
            }
            case INITIAL_TEST_SUBMIT: {
                out = initialTestPrompt(raw);
                break;
            }
            case REFINE_TEST: {
                out = refineTestPrompt(raw);
                break;
            }
            case OBTAIN_ONE_TEST_FROM_EVO:{
                out = obtainOneTestFromEvo(raw);
                break;
            }

            default:
                out = raw;
        }
        return out;
    }

    private static String obtainOneTestFromEvo(String raw) {
        return "Below is the test suites automatically generated by Evosuite. " +
                "However, the test may not perfectly match the requirements. " +
                "For example, some method chain logic may not match the assignment context " +
                "and some aspects may not be covered by tests. " +
                "As a professional unit test specialist, please first read the following generated tests, " +
                "then combined with the previous knowledge of assignment pdf content, " +
                "propose a complete, refined test code with proper comment. The test code are provided below. " +
                "The provided format is filename: content. You just need to provided a complete, refined, commented test code.\n" +
                DOUBLE_BLANK_LINE +
                raw +
                DOUBLE_BLANK_LINE +
                "That all about the original code. Now take a deep beathe, and propose a complete, refined, commented test code.";
    }

    private static String refineTestPrompt(String raw) {
        return "Below is the original unit test. Please refine or add new test cases to make it more complete, based on " +
                "the former PDF content. You need to give a complete test code. Here are the original unit test code.'''Java\n"+raw +"\n'''";
    }

    private static String pdfPrompt(String pdfContent){
        return "As a unit test specialist, I need you to help me with the refinement of some Java unit test, which is for an assignment." +
                "Below is the PDF content of an assignment, please understand the content and prepare for the upcoming test."
                + pdfContent;
    }

    private static String initialTestPrompt(String testFileContent){
        return "Below is the original unit test. Please refine or add new test cases to make it more complete, based on " +
                "the former PDF content. You need to give a complete test code. Here are the original unit test code.'''Java\n"+testFileContent +"\n'''";
    }
}
